site_name: unknown-networks
site_author: dta314
site_url: https://unknown-networks.com

#repo_name: 
#repo_url: 

use_directory_urls: false

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
  - pymdownx.tilde
  - tables
  - toc:
      permalink: '#'

plugins:
  # - meta  # ! insider only, and must put before blog plugin
  - blog:
      blog_dir: .
      post_url_date_format: yyyy/MM
      categories_allowed:
  - rss:
      categories:
        - categories
        - tags
      date_from_meta:
        as_creation: date.created
      match_path: posts/.*
      comments_path: "#__comments"
  - search:
 
theme:
  name: kpn
#  font:
#    code: Roboto Mono
#    text: Roboto